### ISSUE TITLE
Make it a package with submodules ui, console, etc.

### ISSUE THREAD

**Issue by dgelessus** [The-Penultimate-Defenestrator/Pythonista-Tweaks#2]
As I previously suggested on the forums:

> Would it make sense to structure this as submodules, such as `pythonista.editor`, `pythonista.console`, `pythonista.ui`, and so on? Those modules could also `from`-`import` all functions and classes from the standard `editor`/`console`/`ui`/etc. modules. Then you could use both the standard Pythonista functions and the ones written with `objc_util` in the same way.

Would this be okay? If so, I could probably make a quick PR.

**Comment by controversial** [comment]
This would be great

**Comment by controversial** [comment]
Done! Thanks for the suggestion.
